fix: Fix perl-xCAT build with sbuild
Signed-off-by: Daniel Hilst Selli <392820+dhilst@users.noreply.github.com>

diff --git a/perl-xCAT/debian/postrm b/perl-xCAT/debian/postrm
--- a/perl-xCAT/debian/postrm
+++ b/perl-xCAT/debian/postrm
@@ -6,33 +6,33 @@
 set -e
 
 # summary of how this script can be called:
-#        * <postrm> `remove'
-#        * <postrm> `purge'
-#        * <old-postrm> `upgrade' <new-version>
-#        * <new-postrm> `failed-upgrade' <old-version>
-#        * <new-postrm> `abort-install'
-#        * <new-postrm> `abort-install' <old-version>
-#        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <overwriter>
-#          <overwriter-version>
+#				 * <postrm> `remove'
+#				 * <postrm> `purge'
+#				 * <old-postrm> `upgrade' <new-version>
+#				 * <new-postrm> `failed-upgrade' <old-version>
+#				 * <new-postrm> `abort-install'
+#				 * <new-postrm> `abort-install' <old-version>
+#				 * <new-postrm> `abort-upgrade' <old-version>
+#				 * <disappearer's-postrm> `disappear' <overwriter>
+#					 <overwriter-version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
-    upgrade)
+		upgrade)
 	if [ -x /etc/init.d/xcatd ] && [ -f "/proc/cmdline" ]; then
-	    . /etc/profile.d/xcat.sh
-	    /etc/init.d/xcatd reload
+			. /etc/profile.d/xcat.sh
+			invoke-rc.d xcatd reload || true
 	fi
-    ;;
-    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
-    ;;
+		;;
+		purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
+		;;
 
-    *)
-        echo "postrm called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
+		*)
+				echo "postrm called with unknown argument \`$1'" >&2
+				exit 1
+		;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
